In [1]:
!pip install apyori

Collecting apyori
  Downloading apyori-1.1.2.tar.gz (8.6 kB)
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: apyori
  Building wheel for apyori (setup.py) ... done
  Created wheel for apyori: filename=apyori-1.1.2-py3-none-any.whl size=5954 sha256=c601c9616ae0f6da2a319d1e486d6d2f674682d9f071fee23d83809396a05807
  Stored in directory: /root/.cache/pip/wheels/7f/49/e3/42c73b19a264de37129fadaa0c52f26cf50e87de08fb9804af
Successfully built apyori
Installing collected packages: apyori
Successfully installed apyori-1.1.2

In [2]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [8]:
transactions = []

with open("groceries.csv", "r") as file:
    for line in file:
        transactions.append(line.strip().split(","))

In [9]:
print(transactions[:5])

[['citrus fruit', 'semi-finished bread', 'margarine', 'ready soups'], ['tropical fruit', 'yogurt', 'coffee'], ['whole milk'], ['pip fruit', 'yogurt', 'cream cheese', 'meat spreads'], ['other vegetables', 'whole milk', 'condensed milk', 'long life bakery product']]

In [11]:
from apyori import apriori
rules = apriori(transactions = transactions,min_support=0.005,min_confidence=0.2,min_lift=3,min_lenght=2,max_lenght=2)

In [12]:
results = list(rules)

In [13]:
results

[RelationRecord(items=frozenset({'beef', 'root vegetables'}), support=0.017386883579054397, ordered_statistics=[OrderedStatistic(items_base=frozenset({'beef'}), items_add=frozenset({'root vegetables'}), confidence=0.3313953488372093, lift=3.0403668431100312)]),
 RelationRecord(items=frozenset({'berries', 'whipped/sour cream'}), support=0.009049313675648195, ordered_statistics=[OrderedStatistic(items_base=frozenset({'berries'}), items_add=frozenset({'whipped/sour cream'}), confidence=0.27217125382262997, lift=3.796885505454703)]),
 RelationRecord(items=frozenset({'herbs', 'root vegetables'}), support=0.007015760040671073, ordered_statistics=[OrderedStatistic(items_base=frozenset({'herbs'}), items_add=frozenset({'root vegetables'}), confidence=0.43124999999999997, lift=3.956477378731343)]),
 RelationRecord(items=frozenset({'sausage', 'sliced cheese'}), support=0.007015760040671073, ordered_statistics=[OrderedStatistic(items_base=frozenset({'sliced cheese'}), items_add=frozenset({'sausage'}), confidence=0.2863070539419087, lift=3.047434930215013)]),
 RelationRecord(items=frozenset({'beef', 'root vegetables', 'other vegetables'}), support=0.007930859176410779, ordered_statistics=[OrderedStatistic(items_base=frozenset({'beef', 'other vegetables'}), items_add=frozenset({'root vegetables'}), confidence=0.40206185567010316, lift=3.688692491152486)]),
 RelationRecord(items=frozenset({'beef', 'whole milk', 'root vegetables'}), support=0.008032536858159633, ordered_statistics=[OrderedStatistic(items_base=frozenset({'beef', 'whole milk'}), items_add=frozenset({'root vegetables'}), confidence=0.37799043062200954, lift=3.467850639148754)]),
 RelationRecord(items=frozenset({'whole milk', 'domestic eggs', 'butter'}), support=0.005998983223182512, ordered_statistics=[OrderedStatistic(items_base=frozenset({'whole milk', 'butter'}), items_add=frozenset({'domestic eggs'}), confidence=0.21771217712177124, lift=3.4314090737061216), OrderedStatistic(items_base=frozenset({'whole milk', 'domestic eggs'}), items_add=frozenset({'butter'}), confidence=0.2, lift=3.6091743119266058)]),
 RelationRecord(items=frozenset({'root vegetables', 'butter', 'other vegetables'}), support=0.0066090493136756485, ordered_statistics=[OrderedStatistic(items_base=frozenset({'butter', 'other vegetables'}), items_add=frozenset({'root vegetables'}), confidence=0.3299492385786802, lift=3.027099590878097)]),
 RelationRecord(items=frozenset({'whipped/sour cream', 'butter', 'other vegetables'}), support=0.005795627859684799, ordered_statistics=[OrderedStatistic(items_base=frozenset({'butter', 'other vegetables'}), items_add=frozenset({'whipped/sour cream'}), confidence=0.2893401015228426, lift=4.036397019116535), OrderedStatistic(items_base=frozenset({'whipped/sour cream', 'other vegetables'}), items_add=frozenset({'butter'}), confidence=0.2007042253521127, lift=3.6218826721798685)]),
 RelationRecord(items=frozenset({'whole milk', 'butter', 'whipped/sour cream'}), support=0.006710726995424504, ordered_statistics=[OrderedStatistic(items_base=frozenset({'whole milk', 'butter'}), items_add=frozenset({'whipped/sour cream'}), confidence=0.24354243542435425, lift=3.397503336735495), OrderedStatistic(items_base=frozenset({'whole milk', 'whipped/sour cream'}), items_add=frozenset({'butter'}), confidence=0.20820189274447948, lift=3.7571846149393684)]),
 RelationRecord(items=frozenset({'chicken', 'root vegetables', 'whole milk'}), support=0.005998983223182512, ordered_statistics=[OrderedStatistic(items_base=frozenset({'chicken', 'whole milk'}), items_add=frozenset({'root vegetables'}), confidence=0.34104046242774566, lift=3.1288553619187303)]),
 RelationRecord(items=frozenset({'citrus fruit', 'root vegetables', 'other vegetables'}), support=0.010371123538383325, ordered_statistics=[OrderedStatistic(items_base=frozenset({'citrus fruit', 'other vegetables'}), items_add=frozenset({'root vegetables'}), confidence=0.3591549295774648, lift=3.295045459323103), OrderedStatistic(items_base=frozenset({'citrus fruit', 'root vegetables'}), items_add=frozenset({'other vegetables'}), confidence=0.5862068965517241, lift=3.0296084222733612)]),
 RelationRecord(items=frozenset({'citrus fruit', 'tropical fruit', 'other vegetables'}), support=0.009049313675648195, ordered_statistics=[OrderedStatistic(items_base=frozenset({'tropical fruit', 'other vegetables'}), items_add=frozenset({'citrus fruit'}), confidence=0.2521246458923513, lift=3.0462480250015664)]),
 RelationRecord(items=frozenset({'citrus fruit', 'tropical fruit', 'pip fruit'}), support=0.005592272496187087, ordered_statistics=[OrderedStatistic(items_base=frozenset({'citrus fruit', 'pip fruit'}), items_add=frozenset({'tropical fruit'}), confidence=0.4044117647058823, lift=3.8540597925216593), OrderedStatistic(items_base=frozenset({'citrus fruit', 'tropical fruit'}), items_add=frozenset({'pip fruit'}), confidence=0.28061224489795916, lift=3.709437403993855), OrderedStatistic(items_base=frozenset({'tropical fruit', 'pip fruit'}), items_add=frozenset({'citrus fruit'}), confidence=0.27363184079601993, lift=3.306104612074762)]),
 RelationRecord(items=frozenset({'tropical fruit', 'citrus fruit', 'root vegetables'}), support=0.0056939501779359435, ordered_statistics=[OrderedStatistic(items_base=frozenset({'citrus fruit', 'root vegetables'}), items_add=frozenset({'tropical fruit'}), confidence=0.3218390804597701, lift=3.0671389111645726), OrderedStatistic(items_base=frozenset({'tropical fruit', 'root vegetables'}), items_add=frozenset({'citrus fruit'}), confidence=0.2705314009661836, lift=3.268644138209356)]),
 RelationRecord(items=frozenset({'yogurt', 'curd', 'tropical fruit'}), support=0.0052872394509405184, ordered_statistics=[OrderedStatistic(items_base=frozenset({'curd', 'tropical fruit'}), items_add=frozenset({'yogurt'}), confidence=0.5148514851485149, lift=3.6906445746615475)]),
 RelationRecord(items=frozenset({'curd', 'whole milk', 'whipped/sour cream'}), support=0.005897305541433655, ordered_statistics=[OrderedStatistic(items_base=frozenset({'curd', 'whole milk'}), items_add=frozenset({'whipped/sour cream'}), confidence=0.22568093385214008, lift=3.148329055937302)]),
 RelationRecord(items=frozenset({'margarine', 'whole milk', 'domestic eggs'}), support=0.005185561769191663, ordered_statistics=[OrderedStatistic(items_base=frozenset({'margarine', 'whole milk'}), items_add=frozenset({'domestic eggs'}), confidence=0.2142857142857143, lift=3.3774038461538463)]),
 RelationRecord(items=frozenset({'root vegetables', 'domestic eggs', 'other vegetables'}), support=0.007320793085917641, ordered_statistics=[OrderedStatistic(items_base=frozenset({'domestic eggs', 'other vegetables'}), items_add=frozenset({'root vegetables'}), confidence=0.32876712328767127, lift=3.016254344714783)]),
 RelationRecord(items=frozenset({'whipped/sour cream', 'domestic eggs', 'other vegetables'}), support=0.005083884087442806, ordered_statistics=[OrderedStatistic(items_base=frozenset({'domestic eggs', 'other vegetables'}), items_add=frozenset({'whipped/sour cream'}), confidence=0.228310502283105, lift=3.185012468020337)]),
 RelationRecord(items=frozenset({'frozen vegetables', 'root vegetables', 'other vegetables'}), support=0.006100660904931368, ordered_statistics=[OrderedStatistic(items_base=frozenset({'frozen vegetables', 'other vegetables'}), items_add=frozenset({'root vegetables'}), confidence=0.3428571428571428, lift=3.145522388059701)]),
 RelationRecord(items=frozenset({'onions', 'root vegetables', 'other vegetables'}), support=0.0056939501779359435, ordered_statistics=[OrderedStatistic(items_base=frozenset({'onions', 'other vegetables'}), items_add=frozenset({'root vegetables'}), confidence=0.4, lift=3.6697761194029854), OrderedStatistic(items_base=frozenset({'onions', 'root vegetables'}), items_add=frozenset({'other vegetables'}), confidence=0.6021505376344086, lift=3.11200763932444)]),
 RelationRecord(items=frozenset({'pip fruit', 'tropical fruit', 'other vegetables'}), support=0.00945602440264362, ordered_statistics=[OrderedStatistic(items_base=frozenset({'pip fruit', 'other vegetables'}), items_add=frozenset({'tropical fruit'}), confidence=0.3618677042801557, lift=3.4486132476698947), OrderedStatistic(items_base=frozenset({'tropical fruit', 'other vegetables'}), items_add=frozenset({'pip fruit'}), confidence=0.26345609065155806, lift=3.482648725212464)]),
 RelationRecord(items=frozenset({'pip fruit', 'whipped/sour cream', 'other vegetables'}), support=0.005592272496187087, ordered_statistics=[OrderedStatistic(items_base=frozenset({'whipped/sour cream', 'pip fruit'}), items_add=frozenset({'other vegetables'}), confidence=0.6043956043956045, lift=3.1236104935526905)]),
 RelationRecord(items=frozenset({'tropical fruit', 'root vegetables', 'other vegetables'}), support=0.012302999491611592, ordered_statistics=[OrderedStatistic(items_base=frozenset({'tropical fruit', 'other vegetables'}), items_add=frozenset({'root vegetables'}), confidence=0.34277620396600567, lift=3.144779819035136), OrderedStatistic(items_base=frozenset({'tropical fruit', 'root vegetables'}), items_add=frozenset({'other vegetables'}), confidence=0.5845410628019324, lift=3.020999134344196)]),
 RelationRecord(items=frozenset({'whipped/sour cream', 'tropical fruit', 'other vegetables'}), support=0.007829181494661922, ordered_statistics=[OrderedStatistic(items_base=frozenset({'tropical fruit', 'other vegetables'}), items_add=frozenset({'whipped/sour cream'}), confidence=0.21813031161473087, lift=3.042995198199827)]),
 RelationRecord(items=frozenset({'whipped/sour cream', 'yogurt', 'other vegetables'}), support=0.010167768174885612, ordered_statistics=[OrderedStatistic(items_base=frozenset({'yogurt', 'other vegetables'}), items_add=frozenset({'whipped/sour cream'}), confidence=0.23419203747072598, lift=3.2670619695384255)]),
 RelationRecord(items=frozenset({'tropical fruit', 'root vegetables', 'pip fruit'}), support=0.0052872394509405184, ordered_statistics=[OrderedStatistic(items_base=frozenset({'root vegetables', 'pip fruit'}), items_add=frozenset({'tropical fruit'}), confidence=0.33986928104575165, lift=3.238967421593961), OrderedStatistic(items_base=frozenset({'tropical fruit', 'root vegetables'}), items_add=frozenset({'pip fruit'}), confidence=0.25120772946859904, lift=3.3207365851124617)]),
 RelationRecord(items=frozenset({'yogurt', 'tropical fruit', 'pip fruit'}), support=0.006405693950177936, ordered_statistics=[OrderedStatistic(items_base=frozenset({'yogurt', 'pip fruit'}), items_add=frozenset({'tropical fruit'}), confidence=0.3559322033898305, lift=3.3920476941269215)]),
 RelationRecord(items=frozenset({'rolls/buns', 'shopping bags', 'sausage'}), support=0.005998983223182512, ordered_statistics=[OrderedStatistic(items_base=frozenset({'rolls/buns', 'shopping bags'}), items_add=frozenset({'sausage'}), confidence=0.3072916666666667, lift=3.2707938762626267)]),
 RelationRecord(items=frozenset({'tropical fruit', 'yogurt', 'root vegetables'}), support=0.00813421453990849, ordered_statistics=[OrderedStatistic(items_base=frozenset({'yogurt', 'root vegetables'}), items_add=frozenset({'tropical fruit'}), confidence=0.31496062992125984, lift=3.00158701092596)]),
 RelationRecord(items=frozenset({'yogurt', 'root vegetables', 'whipped/sour cream'}), support=0.006405693950177936, ordered_statistics=[OrderedStatistic(items_base=frozenset({'yogurt', 'root vegetables'}), items_add=frozenset({'whipped/sour cream'}), confidence=0.2480314960629921, lift=3.4601273245099677)]),
 RelationRecord(items=frozenset({'yogurt', 'tropical fruit', 'whipped/sour cream'}), support=0.0062023385866802234, ordered_statistics=[OrderedStatistic(items_base=frozenset({'tropical fruit', 'whipped/sour cream'}), items_add=frozenset({'yogurt'}), confidence=0.44852941176470584, lift=3.215223589435774)]),
 RelationRecord(items=frozenset({'whole milk', 'citrus fruit', 'root vegetables', 'other vegetables'}), support=0.005795627859684799, ordered_statistics=[OrderedStatistic(items_base=frozenset({'citrus fruit', 'other vegetables'}), items_add=frozenset({'whole milk', 'root vegetables'}), confidence=0.2007042253521127, lift=4.103796374923136), OrderedStatistic(items_base=frozenset({'citrus fruit', 'root vegetables'}), items_add=frozenset({'whole milk', 'other vegetables'}), confidence=0.3275862068965517, lift=4.377459707646177), OrderedStatistic(items_base=frozenset({'whole milk', 'citrus fruit', 'other vegetables'}), items_add=frozenset({'root vegetables'}), confidence=0.4453125, lift=4.085492945429104), OrderedStatistic(items_base=frozenset({'whole milk', 'citrus fruit', 'root vegetables'}), items_add=frozenset({'other vegetables'}), confidence=0.6333333333333333, lift=3.2731651777894553), OrderedStatistic(items_base=frozenset({'whole milk', 'root vegetables', 'other vegetables'}), items_add=frozenset({'citrus fruit'}), confidence=0.25, lift=3.0205773955773956)]),
 RelationRecord(items=frozenset({'yogurt', 'whole milk', 'fruit/vegetable juice', 'other vegetables'}), support=0.005083884087442806, ordered_statistics=[OrderedStatistic(items_base=frozenset({'fruit/vegetable juice', 'other vegetables'}), items_add=frozenset({'yogurt', 'whole milk'}), confidence=0.24154589371980675, lift=4.3114407708426485), OrderedStatistic(items_base=frozenset({'yogurt', 'fruit/vegetable juice'}), items_add=frozenset({'whole milk', 'other vegetables'}), confidence=0.2717391304347826, lift=3.631187972589792), OrderedStatistic(items_base=frozenset({'whole milk', 'fruit/vegetable juice', 'other vegetables'}), items_add=frozenset({'yogurt'}), confidence=0.4854368932038835, lift=3.4797899742421237), OrderedStatistic(items_base=frozenset({'yogurt', 'whole milk', 'other vegetables'}), items_add=frozenset({'fruit/vegetable juice'}), confidence=0.228310502283105, lift=3.158134725674174)]),
 RelationRecord(items=frozenset({'pip fruit', 'whole milk', 'root vegetables', 'other vegetables'}), support=0.005490594814438231, ordered_statistics=[OrderedStatistic(items_base=frozenset({'pip fruit', 'other vegetables'}), items_add=frozenset({'whole milk', 'root vegetables'}), confidence=0.21011673151750973, lift=4.29625375150667), OrderedStatistic(items_base=frozenset({'root vegetables', 'pip fruit'}), items_add=frozenset({'whole milk', 'other vegetables'}), confidence=0.35294117647058826, lift=4.716272378516624), OrderedStatistic(items_base=frozenset({'pip fruit', 'whole milk', 'other vegetables'}), items_add=frozenset({'root vegetables'}), confidence=0.40601503759398494, lift=3.724960722702278), OrderedStatistic(items_base=frozenset({'whole milk', 'root vegetables', 'other vegetables'}), items_add=frozenset({'pip fruit'}), confidence=0.2368421052631579, lift=3.1308361629881154), OrderedStatistic(items_base=frozenset({'whole milk', 'root vegetables', 'pip fruit'}), items_add=frozenset({'other vegetables'}), confidence=0.6136363636363636, lift=3.1713681746524625)]),
 RelationRecord(items=frozenset({'pip fruit', 'yogurt', 'whole milk', 'other vegetables'}), support=0.005083884087442806, ordered_statistics=[OrderedStatistic(items_base=frozenset({'yogurt', 'pip fruit'}), items_add=frozenset({'whole milk', 'other vegetables'}), confidence=0.2824858757062147, lift=3.7747942765905185), OrderedStatistic(items_base=frozenset({'yogurt', 'whole milk', 'other vegetables'}), items_add=frozenset({'pip fruit'}), confidence=0.228310502283105, lift=3.0180561692934647)]),
 RelationRecord(items=frozenset({'rolls/buns', 'whole milk', 'root vegetables', 'other vegetables'}), support=0.0062023385866802234, ordered_statistics=[OrderedStatistic(items_base=frozenset({'rolls/buns', 'root vegetables'}), items_add=frozenset({'whole milk', 'other vegetables'}), confidence=0.25523012552301255, lift=3.4105819083136257), OrderedStatistic(items_base=frozenset({'rolls/buns', 'whole milk', 'other vegetables'}), items_add=frozenset({'root vegetables'}), confidence=0.3465909090909091, lift=3.179777603459973)]),
 RelationRecord(items=frozenset({'tropical fruit', 'whole milk', 'root vegetables', 'other vegetables'}), support=0.007015760040671073, ordered_statistics=[OrderedStatistic(items_base=frozenset({'tropical fruit', 'root vegetables'}), items_add=frozenset({'whole milk', 'other vegetables'}), confidence=0.33333333333333337, lift=4.454257246376812), OrderedStatistic(items_base=frozenset({'whole milk', 'tropical fruit', 'other vegetables'}), items_add=frozenset({'root vegetables'}), confidence=0.4107142857142857, lift=3.7680736940298507), OrderedStatistic(items_base=frozenset({'tropical fruit', 'whole milk', 'root vegetables'}), items_add=frozenset({'other vegetables'}), confidence=0.5847457627118644, lift=3.0220570553185424)]),
 RelationRecord(items=frozenset({'whipped/sour cream', 'whole milk', 'root vegetables', 'other vegetables'}), support=0.005185561769191663, ordered_statistics=[OrderedStatistic(items_base=frozenset({'root vegetables', 'whipped/sour cream'}), items_add=frozenset({'whole milk', 'other vegetables'}), confidence=0.30357142857142855, lift=4.056555706521739), OrderedStatistic(items_base=frozenset({'whole milk', 'root vegetables', 'other vegetables'}), items_add=frozenset({'whipped/sour cream'}), confidence=0.2236842105263158, lift=3.120474057484136), OrderedStatistic(items_base=frozenset({'whipped/sour cream', 'whole milk', 'other vegetables'}), items_add=frozenset({'root vegetables'}), confidence=0.3541666666666667, lift=3.2492809390547266)]),
 RelationRecord(items=frozenset({'yogurt', 'whole milk', 'root vegetables', 'other vegetables'}), support=0.007829181494661922, ordered_statistics=[OrderedStatistic(items_base=frozenset({'yogurt', 'root vegetables'}), items_add=frozenset({'whole milk', 'other vegetables'}), confidence=0.3031496062992126, lift=4.050918991783636), OrderedStatistic(items_base=frozenset({'yogurt', 'whole milk', 'other vegetables'}), items_add=frozenset({'root vegetables'}), confidence=0.35159817351598177, lift=3.2257164519866426)]),
 RelationRecord(items=frozenset({'yogurt', 'whole milk', 'tropical fruit', 'other vegetables'}), support=0.007625826131164209, ordered_statistics=[OrderedStatistic(items_base=frozenset({'tropical fruit', 'other vegetables'}), items_add=frozenset({'yogurt', 'whole milk'}), confidence=0.21246458923512745, lift=3.7923579584890716), OrderedStatistic(items_base=frozenset({'yogurt', 'tropical fruit'}), items_add=frozenset({'whole milk', 'other vegetables'}), confidence=0.2604166666666667, lift=3.4798884737318843), OrderedStatistic(items_base=frozenset({'whole milk', 'tropical fruit', 'other vegetables'}), items_add=frozenset({'yogurt'}), confidence=0.4464285714285714, lift=3.200163994169096), OrderedStatistic(items_base=frozenset({'yogurt', 'whole milk', 'other vegetables'}), items_add=frozenset({'tropical fruit'}), confidence=0.34246575342465757, lift=3.2637119040033986)]),
 RelationRecord(items=frozenset({'whipped/sour cream', 'yogurt', 'whole milk', 'other vegetables'}), support=0.005592272496187087, ordered_statistics=[OrderedStatistic(items_base=frozenset({'yogurt', 'whipped/sour cream'}), items_add=frozenset({'whole milk', 'other vegetables'}), confidence=0.2696078431372549, lift=3.602708066922421), OrderedStatistic(items_base=frozenset({'yogurt', 'whole milk', 'other vegetables'}), items_add=frozenset({'whipped/sour cream'}), confidence=0.2511415525114155, lift=3.503513714822371)]),

In [14]:
def inspect(results):
    lhs         = [tuple(result[2][0][0])[0] for result in results]
    rhs         = [tuple(result[2][0][1])[0] for result in results]
    supports    = [result[1] for result in results]
    confidences = [result[2][0][2] for result in results]
    lifts       = [result[2][0][3] for result in results]
    return list(zip(lhs, rhs, supports, confidences, lifts))
resultsinDataFrame = pd.DataFrame(inspect(results), columns = ['Left Hand Side', 'Right Hand Side', 'Support', 'Confidence', 'Lift'])

In [15]:
resultsinDataFrame

           Left Hand Side     Right Hand Side   Support  Confidence      Lift
0                    beef     root vegetables  0.017387    0.331395  3.040367
1                 berries  whipped/sour cream  0.009049    0.272171  3.796886
2                   herbs     root vegetables  0.007016    0.431250  3.956477
3           sliced cheese             sausage  0.007016    0.286307  3.047435
4                    beef     root vegetables  0.007931    0.402062  3.688692
5                    beef     root vegetables  0.008033    0.377990  3.467851
6              whole milk       domestic eggs  0.005999    0.217712  3.431409
7                  butter     root vegetables  0.006609    0.329949  3.027100
8                  butter  whipped/sour cream  0.005796    0.289340  4.036397
9              whole milk  whipped/sour cream  0.006711    0.243542  3.397503
10                chicken     root vegetables  0.005999    0.341040  3.128855
11           citrus fruit     root vegetables  0.010371    0.359155  3.295045
12         tropical fruit        citrus fruit  0.009049    0.252125  3.046248
13           citrus fruit      tropical fruit  0.005592    0.404412  3.854060
14           citrus fruit      tropical fruit  0.005694    0.321839  3.067139
15                   curd              yogurt  0.005287    0.514851  3.690645
16                   curd  whipped/sour cream  0.005897    0.225681  3.148329
17              margarine       domestic eggs  0.005186    0.214286  3.377404
18          domestic eggs     root vegetables  0.007321    0.328767  3.016254
19          domestic eggs  whipped/sour cream  0.005084    0.228311  3.185012
20      frozen vegetables     root vegetables  0.006101    0.342857  3.145522
21                 onions     root vegetables  0.005694    0.400000  3.669776
22              pip fruit      tropical fruit  0.009456    0.361868  3.448613
23     whipped/sour cream    other vegetables  0.005592    0.604396  3.123610
24         tropical fruit     root vegetables  0.012303    0.342776  3.144780
25         tropical fruit  whipped/sour cream  0.007829    0.218130  3.042995
26                 yogurt  whipped/sour cream  0.010168    0.234192  3.267062
27        root vegetables      tropical fruit  0.005287    0.339869  3.238967
28                 yogurt      tropical fruit  0.006406    0.355932  3.392048
29             rolls/buns             sausage  0.005999    0.307292  3.270794
30                 yogurt      tropical fruit  0.008134    0.314961  3.001587
31                 yogurt  whipped/sour cream  0.006406    0.248031  3.460127
32         tropical fruit              yogurt  0.006202    0.448529  3.215224
33           citrus fruit          whole milk  0.005796    0.200704  4.103796
34  fruit/vegetable juice              yogurt  0.005084    0.241546  4.311441
35              pip fruit          whole milk  0.005491    0.210117  4.296254
36                 yogurt          whole milk  0.005084    0.282486  3.774794
37             rolls/buns          whole milk  0.006202    0.255230  3.410582
38         tropical fruit          whole milk  0.007016    0.333333  4.454257
39        root vegetables          whole milk  0.005186    0.303571  4.056556
40                 yogurt          whole milk  0.007829    0.303150  4.050919
41         tropical fruit              yogurt  0.007626    0.212465  3.792358
42                 yogurt          whole milk  0.005592    0.269608  3.602708
43         tropical fruit              yogurt  0.005694    0.270531  4.828814

In [16]:
resultsinDataFrame.nlargest(n = 10, columns = 'Lift')

           Left Hand Side     Right Hand Side   Support  Confidence      Lift
43         tropical fruit              yogurt  0.005694    0.270531  4.828814
38         tropical fruit          whole milk  0.007016    0.333333  4.454257
34  fruit/vegetable juice              yogurt  0.005084    0.241546  4.311441
35              pip fruit          whole milk  0.005491    0.210117  4.296254
33           citrus fruit          whole milk  0.005796    0.200704  4.103796
39        root vegetables          whole milk  0.005186    0.303571  4.056556
40                 yogurt          whole milk  0.007829    0.303150  4.050919
8                  butter  whipped/sour cream  0.005796    0.289340  4.036397
2                   herbs     root vegetables  0.007016    0.431250  3.956477
13           citrus fruit      tropical fruit  0.005592    0.404412  3.854060

In [17]:
resultsinDataFrame.nlargest(n = 15, columns = 'Confidence')

        Left Hand Side   Right Hand Side   Support  Confidence      Lift
23  whipped/sour cream  other vegetables  0.005592    0.604396  3.123610
15                curd            yogurt  0.005287    0.514851  3.690645
32      tropical fruit            yogurt  0.006202    0.448529  3.215224
2                herbs   root vegetables  0.007016    0.431250  3.956477
13        citrus fruit    tropical fruit  0.005592    0.404412  3.854060
4                 beef   root vegetables  0.007931    0.402062  3.688692
21              onions   root vegetables  0.005694    0.400000  3.669776
5                 beef   root vegetables  0.008033    0.377990  3.467851
22           pip fruit    tropical fruit  0.009456    0.361868  3.448613
11        citrus fruit   root vegetables  0.010371    0.359155  3.295045
28              yogurt    tropical fruit  0.006406    0.355932  3.392048
20   frozen vegetables   root vegetables  0.006101    0.342857  3.145522
24      tropical fruit   root vegetables  0.012303    0.342776  3.144780
10             chicken   root vegetables  0.005999    0.341040  3.128855
27     root vegetables    tropical fruit  0.005287    0.339869  3.238967